// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catering_packages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkDateAvailability = `-- name: CheckDateAvailability :one
SELECT COUNT(*) FROM catering_details cd
JOIN orders o ON o.id = cd.order_id
WHERE cd.event_date = $1 AND o.status != 'cancelled'
`

// Returns count of existing (non-cancelled) catering bookings on a given date,
// so the service layer can flag the date as busy without hard-blocking it.
func (q *Queries) CheckDateAvailability(ctx context.Context, eventDate pgtype.Date) (int64, error) {
	row := q.db.QueryRow(ctx, checkDateAvailability, eventDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCateringPackage = `-- name: CreateCateringPackage :one
INSERT INTO catering_packages (name, description, price_per_guest, flat_price, min_guests, image_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, price_per_guest, flat_price, min_guests, is_active, created_at, updated_at, image_url
`

type CreateCateringPackageParams struct {
	Name          string         `json:"name"`
	Description   pgtype.Text    `json:"description"`
	PricePerGuest pgtype.Numeric `json:"price_per_guest"`
	FlatPrice     pgtype.Numeric `json:"flat_price"`
	MinGuests     pgtype.Int4    `json:"min_guests"`
	ImageUrl      pgtype.Text    `json:"image_url"`
}

func (q *Queries) CreateCateringPackage(ctx context.Context, arg CreateCateringPackageParams) (CateringPackage, error) {
	row := q.db.QueryRow(ctx, createCateringPackage,
		arg.Name,
		arg.Description,
		arg.PricePerGuest,
		arg.FlatPrice,
		arg.MinGuests,
		arg.ImageUrl,
	)
	var i CateringPackage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PricePerGuest,
		&i.FlatPrice,
		&i.MinGuests,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const deleteCateringPackage = `-- name: DeleteCateringPackage :exec
UPDATE catering_packages SET is_active = false WHERE id = $1
`

func (q *Queries) DeleteCateringPackage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCateringPackage, id)
	return err
}

const getCateringPackageByID = `-- name: GetCateringPackageByID :one
SELECT id, name, description, price_per_guest, flat_price, min_guests, is_active, created_at, updated_at, image_url FROM catering_packages WHERE id = $1
`

func (q *Queries) GetCateringPackageByID(ctx context.Context, id pgtype.UUID) (CateringPackage, error) {
	row := q.db.QueryRow(ctx, getCateringPackageByID, id)
	var i CateringPackage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PricePerGuest,
		&i.FlatPrice,
		&i.MinGuests,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const listActiveCateringPackages = `-- name: ListActiveCateringPackages :many
SELECT id, name, description, price_per_guest, flat_price, min_guests, is_active, created_at, updated_at, image_url FROM catering_packages
WHERE is_active = true
ORDER BY name ASC
`

func (q *Queries) ListActiveCateringPackages(ctx context.Context) ([]CateringPackage, error) {
	rows, err := q.db.Query(ctx, listActiveCateringPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CateringPackage{}
	for rows.Next() {
		var i CateringPackage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PricePerGuest,
			&i.FlatPrice,
			&i.MinGuests,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCateringPackage = `-- name: UpdateCateringPackage :one
UPDATE catering_packages
SET name = $2, description = $3, price_per_guest = $4, flat_price = $5, min_guests = $6, image_url = $7
WHERE id = $1
RETURNING id, name, description, price_per_guest, flat_price, min_guests, is_active, created_at, updated_at, image_url
`

type UpdateCateringPackageParams struct {
	ID            pgtype.UUID    `json:"id"`
	Name          string         `json:"name"`
	Description   pgtype.Text    `json:"description"`
	PricePerGuest pgtype.Numeric `json:"price_per_guest"`
	FlatPrice     pgtype.Numeric `json:"flat_price"`
	MinGuests     pgtype.Int4    `json:"min_guests"`
	ImageUrl      pgtype.Text    `json:"image_url"`
}

func (q *Queries) UpdateCateringPackage(ctx context.Context, arg UpdateCateringPackageParams) (CateringPackage, error) {
	row := q.db.QueryRow(ctx, updateCateringPackage,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PricePerGuest,
		arg.FlatPrice,
		arg.MinGuests,
		arg.ImageUrl,
	)
	var i CateringPackage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PricePerGuest,
		&i.FlatPrice,
		&i.MinGuests,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}
