// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catering_details.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCateringDetails = `-- name: CreateCateringDetails :one
INSERT INTO catering_details (
    order_id, catering_package_id, event_date, event_time,
    guest_count, venue_address, custom_request
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, order_id, catering_package_id, event_date, event_time, guest_count, venue_address, custom_request, created_at, updated_at
`

type CreateCateringDetailsParams struct {
	OrderID           pgtype.UUID `json:"order_id"`
	CateringPackageID pgtype.UUID `json:"catering_package_id"`
	EventDate         pgtype.Date `json:"event_date"`
	EventTime         pgtype.Time `json:"event_time"`
	GuestCount        int32       `json:"guest_count"`
	VenueAddress      pgtype.Text `json:"venue_address"`
	CustomRequest     pgtype.Text `json:"custom_request"`
}

func (q *Queries) CreateCateringDetails(ctx context.Context, arg CreateCateringDetailsParams) (CateringDetail, error) {
	row := q.db.QueryRow(ctx, createCateringDetails,
		arg.OrderID,
		arg.CateringPackageID,
		arg.EventDate,
		arg.EventTime,
		arg.GuestCount,
		arg.VenueAddress,
		arg.CustomRequest,
	)
	var i CateringDetail
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CateringPackageID,
		&i.EventDate,
		&i.EventTime,
		&i.GuestCount,
		&i.VenueAddress,
		&i.CustomRequest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCateringDetailsByOrderID = `-- name: GetCateringDetailsByOrderID :one
SELECT id, order_id, catering_package_id, event_date, event_time, guest_count, venue_address, custom_request, created_at, updated_at FROM catering_details WHERE order_id = $1
`

func (q *Queries) GetCateringDetailsByOrderID(ctx context.Context, orderID pgtype.UUID) (CateringDetail, error) {
	row := q.db.QueryRow(ctx, getCateringDetailsByOrderID, orderID)
	var i CateringDetail
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CateringPackageID,
		&i.EventDate,
		&i.EventTime,
		&i.GuestCount,
		&i.VenueAddress,
		&i.CustomRequest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUpcomingCateringBookings = `-- name: ListUpcomingCateringBookings :many
SELECT cd.id, cd.order_id, cd.catering_package_id, cd.event_date, cd.event_time, cd.guest_count, cd.venue_address, cd.custom_request, cd.created_at, cd.updated_at, o.order_number, o.status, c.full_name, c.phone
FROM catering_details cd
JOIN orders o ON o.id = cd.order_id
JOIN customers c ON c.id = o.customer_id
WHERE cd.event_date >= CURRENT_DATE AND o.status != 'cancelled'
ORDER BY cd.event_date ASC
`

type ListUpcomingCateringBookingsRow struct {
	ID                pgtype.UUID        `json:"id"`
	OrderID           pgtype.UUID        `json:"order_id"`
	CateringPackageID pgtype.UUID        `json:"catering_package_id"`
	EventDate         pgtype.Date        `json:"event_date"`
	EventTime         pgtype.Time        `json:"event_time"`
	GuestCount        int32              `json:"guest_count"`
	VenueAddress      pgtype.Text        `json:"venue_address"`
	CustomRequest     pgtype.Text        `json:"custom_request"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	OrderNumber       string             `json:"order_number"`
	Status            string             `json:"status"`
	FullName          string             `json:"full_name"`
	Phone             string             `json:"phone"`
}

// For the admin calendar view.
func (q *Queries) ListUpcomingCateringBookings(ctx context.Context) ([]ListUpcomingCateringBookingsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingCateringBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingCateringBookingsRow{}
	for rows.Next() {
		var i ListUpcomingCateringBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CateringPackageID,
			&i.EventDate,
			&i.EventTime,
			&i.GuestCount,
			&i.VenueAddress,
			&i.CustomRequest,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderNumber,
			&i.Status,
			&i.FullName,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
