// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catering_packages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkDateAvailability = `-- name: CheckDateAvailability :one
SELECT COUNT(*) FROM catering_details cd
JOIN orders o ON o.id = cd.order_id
WHERE cd.event_date = $1 AND o.status != 'cancelled'
`

// Returns count of existing (non-cancelled) catering bookings on a given date,
// so the service layer can flag the date as busy without hard-blocking it.
func (q *Queries) CheckDateAvailability(ctx context.Context, eventDate pgtype.Date) (int64, error) {
	row := q.db.QueryRow(ctx, checkDateAvailability, eventDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCateringPackage = `-- name: CreateCateringPackage :one
INSERT INTO catering_packages (name, description, price_per_guest, flat_price, min_guests)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, price_per_guest, flat_price, min_guests, is_active, created_at, updated_at
`

type CreateCateringPackageParams struct {
	Name          string         `json:"name"`
	Description   pgtype.Text    `json:"description"`
	PricePerGuest pgtype.Numeric `json:"price_per_guest"`
	FlatPrice     pgtype.Numeric `json:"flat_price"`
	MinGuests     pgtype.Int4    `json:"min_guests"`
}

func (q *Queries) CreateCateringPackage(ctx context.Context, arg CreateCateringPackageParams) (CateringPackage, error) {
	row := q.db.QueryRow(ctx, createCateringPackage,
		arg.Name,
		arg.Description,
		arg.PricePerGuest,
		arg.FlatPrice,
		arg.MinGuests,
	)
	var i CateringPackage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PricePerGuest,
		&i.FlatPrice,
		&i.MinGuests,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCateringPackageByID = `-- name: GetCateringPackageByID :one
SELECT id, name, description, price_per_guest, flat_price, min_guests, is_active, created_at, updated_at FROM catering_packages WHERE id = $1
`

func (q *Queries) GetCateringPackageByID(ctx context.Context, id pgtype.UUID) (CateringPackage, error) {
	row := q.db.QueryRow(ctx, getCateringPackageByID, id)
	var i CateringPackage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PricePerGuest,
		&i.FlatPrice,
		&i.MinGuests,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCateringPackages = `-- name: ListActiveCateringPackages :many
SELECT id, name, description, price_per_guest, flat_price, min_guests, is_active, created_at, updated_at FROM catering_packages
WHERE is_active = true
ORDER BY name ASC
`

func (q *Queries) ListActiveCateringPackages(ctx context.Context) ([]CateringPackage, error) {
	rows, err := q.db.Query(ctx, listActiveCateringPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CateringPackage{}
	for rows.Next() {
		var i CateringPackage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PricePerGuest,
			&i.FlatPrice,
			&i.MinGuests,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
