// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomerOrders = `-- name: CountCustomerOrders :one
SELECT COUNT(*) FROM orders WHERE customer_id = $1
`

func (q *Queries) CountCustomerOrders(ctx context.Context, customerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomerOrders, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (full_name, phone, email)
VALUES ($1, $2, $3)
RETURNING id, full_name, phone, email, created_at, updated_at
`

type CreateCustomerParams struct {
	FullName string      `json:"full_name"`
	Phone    string      `json:"phone"`
	Email    pgtype.Text `json:"email"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.FullName, arg.Phone, arg.Email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, full_name, phone, email, created_at, updated_at FROM customers WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, full_name, phone, email, created_at, updated_at FROM customers WHERE phone = $1
`

func (q *Queries) GetCustomerByPhone(ctx context.Context, phone string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, full_name, phone, email, created_at, updated_at FROM customers
WHERE ($3::text IS NULL
       OR full_name ILIKE '%' || $3 || '%'
       OR phone ILIKE '%' || $3 || '%')
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCustomersParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Search pgtype.Text `json:"search"`
}

// Admin customer list, newest first, optionally searched by name or phone.
func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
