// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminUser struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     pgtype.Text        `json:"full_name"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type CateringDetail struct {
	ID                pgtype.UUID        `json:"id"`
	OrderID           pgtype.UUID        `json:"order_id"`
	CateringPackageID pgtype.UUID        `json:"catering_package_id"`
	EventDate         pgtype.Date        `json:"event_date"`
	EventTime         pgtype.Time        `json:"event_time"`
	GuestCount        int32              `json:"guest_count"`
	VenueAddress      pgtype.Text        `json:"venue_address"`
	CustomRequest     pgtype.Text        `json:"custom_request"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type CateringPackage struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	PricePerGuest pgtype.Numeric     `json:"price_per_guest"`
	FlatPrice     pgtype.Numeric     `json:"flat_price"`
	MinGuests     pgtype.Int4        `json:"min_guests"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	ID        pgtype.UUID        `json:"id"`
	FullName  string             `json:"full_name"`
	Phone     string             `json:"phone"`
	Email     pgtype.Text        `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID              pgtype.UUID        `json:"id"`
	OrderNumber     string             `json:"order_number"`
	OrderType       string             `json:"order_type"`
	CustomerID      pgtype.UUID        `json:"customer_id"`
	Status          string             `json:"status"`
	DeliveryMethod  string             `json:"delivery_method"`
	DeliveryAddress pgtype.Text        `json:"delivery_address"`
	ContactPhone    string             `json:"contact_phone"`
	PaymentMethod   string             `json:"payment_method"`
	PaymentStatus   string             `json:"payment_status"`
	Subtotal        pgtype.Numeric     `json:"subtotal"`
	CustomerNotes   pgtype.Text        `json:"customer_notes"`
	AdminNotes      pgtype.Text        `json:"admin_notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID               pgtype.UUID        `json:"id"`
	OrderID          pgtype.UUID        `json:"order_id"`
	ProductVariantID pgtype.UUID        `json:"product_variant_id"`
	Quantity         int32              `json:"quantity"`
	UnitPrice        pgtype.Numeric     `json:"unit_price"`
	LineTotal        pgtype.Numeric     `json:"line_total"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type OrderStatusHistory struct {
	ID        pgtype.UUID        `json:"id"`
	OrderID   pgtype.UUID        `json:"order_id"`
	Status    string             `json:"status"`
	ChangedBy pgtype.UUID        `json:"changed_by"`
	Note      pgtype.Text        `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProductVariant struct {
	ID            pgtype.UUID        `json:"id"`
	ProductID     pgtype.UUID        `json:"product_id"`
	Sku           string             `json:"sku"`
	GrindType     pgtype.Text        `json:"grind_type"`
	WeightGrams   int32              `json:"weight_grams"`
	Price         pgtype.Numeric     `json:"price"`
	StockQuantity int32              `json:"stock_quantity"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
