// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_status_history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderStatusHistory = `-- name: CreateOrderStatusHistory :one
INSERT INTO order_status_history (order_id, status, changed_by, note)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, status, changed_by, note, created_at
`

type CreateOrderStatusHistoryParams struct {
	OrderID   pgtype.UUID `json:"order_id"`
	Status    string      `json:"status"`
	ChangedBy pgtype.UUID `json:"changed_by"`
	Note      pgtype.Text `json:"note"`
}

func (q *Queries) CreateOrderStatusHistory(ctx context.Context, arg CreateOrderStatusHistoryParams) (OrderStatusHistory, error) {
	row := q.db.QueryRow(ctx, createOrderStatusHistory,
		arg.OrderID,
		arg.Status,
		arg.ChangedBy,
		arg.Note,
	)
	var i OrderStatusHistory
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.ChangedBy,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderStatusHistory = `-- name: ListOrderStatusHistory :many
SELECT id, order_id, status, changed_by, note, created_at FROM order_status_history
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOrderStatusHistory(ctx context.Context, orderID pgtype.UUID) ([]OrderStatusHistory, error) {
	rows, err := q.db.Query(ctx, listOrderStatusHistory, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderStatusHistory{}
	for rows.Next() {
		var i OrderStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Status,
			&i.ChangedBy,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
