// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    order_number, order_type, customer_id, delivery_method,
    delivery_address, contact_phone, payment_method, subtotal, customer_notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, order_number, order_type, customer_id, status, delivery_method, delivery_address, contact_phone, payment_method, payment_status, subtotal, customer_notes, admin_notes, created_at, updated_at
`

type CreateOrderParams struct {
	OrderNumber     string         `json:"order_number"`
	OrderType       string         `json:"order_type"`
	CustomerID      pgtype.UUID    `json:"customer_id"`
	DeliveryMethod  string         `json:"delivery_method"`
	DeliveryAddress pgtype.Text    `json:"delivery_address"`
	ContactPhone    string         `json:"contact_phone"`
	PaymentMethod   string         `json:"payment_method"`
	Subtotal        pgtype.Numeric `json:"subtotal"`
	CustomerNotes   pgtype.Text    `json:"customer_notes"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderNumber,
		arg.OrderType,
		arg.CustomerID,
		arg.DeliveryMethod,
		arg.DeliveryAddress,
		arg.ContactPhone,
		arg.PaymentMethod,
		arg.Subtotal,
		arg.CustomerNotes,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.OrderType,
		&i.CustomerID,
		&i.Status,
		&i.DeliveryMethod,
		&i.DeliveryAddress,
		&i.ContactPhone,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.Subtotal,
		&i.CustomerNotes,
		&i.AdminNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, order_number, order_type, customer_id, status, delivery_method, delivery_address, contact_phone, payment_method, payment_status, subtotal, customer_notes, admin_notes, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.OrderType,
		&i.CustomerID,
		&i.Status,
		&i.DeliveryMethod,
		&i.DeliveryAddress,
		&i.ContactPhone,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.Subtotal,
		&i.CustomerNotes,
		&i.AdminNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByOrderNumber = `-- name: GetOrderByOrderNumber :one
SELECT id, order_number, order_type, customer_id, status, delivery_method, delivery_address, contact_phone, payment_method, payment_status, subtotal, customer_notes, admin_notes, created_at, updated_at FROM orders WHERE order_number = $1
`

func (q *Queries) GetOrderByOrderNumber(ctx context.Context, orderNumber string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByOrderNumber, orderNumber)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.OrderType,
		&i.CustomerID,
		&i.Status,
		&i.DeliveryMethod,
		&i.DeliveryAddress,
		&i.ContactPhone,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.Subtotal,
		&i.CustomerNotes,
		&i.AdminNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, order_number, order_type, customer_id, status, delivery_method, delivery_address, contact_phone, payment_method, payment_status, subtotal, customer_notes, admin_notes, created_at, updated_at FROM orders
WHERE ($3::varchar IS NULL OR status = $3)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOrdersParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Status pgtype.Text `json:"status"`
}

// Admin order queue, newest first, optionally filtered by status.
func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.OrderType,
			&i.CustomerID,
			&i.Status,
			&i.DeliveryMethod,
			&i.DeliveryAddress,
			&i.ContactPhone,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.Subtotal,
			&i.CustomerNotes,
			&i.AdminNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOrderNumber = `-- name: NextOrderNumber :one
SELECT nextval('order_number_seq')::bigint
`

func (q *Queries) NextOrderNumber(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextOrderNumber)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, admin_notes = COALESCE($3, admin_notes)
WHERE id = $1
RETURNING id, order_number, order_type, customer_id, status, delivery_method, delivery_address, contact_phone, payment_method, payment_status, subtotal, customer_notes, admin_notes, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
	AdminNotes pgtype.Text `json:"admin_notes"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status, arg.AdminNotes)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.OrderType,
		&i.CustomerID,
		&i.Status,
		&i.DeliveryMethod,
		&i.DeliveryAddress,
		&i.ContactPhone,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.Subtotal,
		&i.CustomerNotes,
		&i.AdminNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
