// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_variant_id, quantity, unit_price, line_total)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, product_variant_id, quantity, unit_price, line_total, created_at
`

type CreateOrderItemParams struct {
	OrderID          pgtype.UUID    `json:"order_id"`
	ProductVariantID pgtype.UUID    `json:"product_variant_id"`
	Quantity         int32          `json:"quantity"`
	UnitPrice        pgtype.Numeric `json:"unit_price"`
	LineTotal        pgtype.Numeric `json:"line_total"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductVariantID,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineTotal,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductVariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.LineTotal,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT oi.id, oi.order_id, oi.product_variant_id, oi.quantity, oi.unit_price, oi.line_total, oi.created_at, pv.sku, pv.grind_type, pv.weight_grams, p.name AS product_name
FROM order_items oi
JOIN product_variants pv ON pv.id = oi.product_variant_id
JOIN products p ON p.id = pv.product_id
WHERE oi.order_id = $1
`

type ListOrderItemsByOrderIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrderID          pgtype.UUID        `json:"order_id"`
	ProductVariantID pgtype.UUID        `json:"product_variant_id"`
	Quantity         int32              `json:"quantity"`
	UnitPrice        pgtype.Numeric     `json:"unit_price"`
	LineTotal        pgtype.Numeric     `json:"line_total"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Sku              string             `json:"sku"`
	GrindType        pgtype.Text        `json:"grind_type"`
	WeightGrams      int32              `json:"weight_grams"`
	ProductName      string             `json:"product_name"`
}

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]ListOrderItemsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsByOrderIDRow{}
	for rows.Next() {
		var i ListOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductVariantID,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
			&i.CreatedAt,
			&i.Sku,
			&i.GrindType,
			&i.WeightGrams,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
