// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_variants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVariant = `-- name: CreateVariant :one
INSERT INTO product_variants (product_id, sku, grind_type, weight_grams, price, stock_quantity)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, sku, grind_type, weight_grams, price, stock_quantity, is_active, created_at, updated_at
`

type CreateVariantParams struct {
	ProductID     pgtype.UUID    `json:"product_id"`
	Sku           string         `json:"sku"`
	GrindType     pgtype.Text    `json:"grind_type"`
	WeightGrams   int32          `json:"weight_grams"`
	Price         pgtype.Numeric `json:"price"`
	StockQuantity int32          `json:"stock_quantity"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.ProductID,
		arg.Sku,
		arg.GrindType,
		arg.WeightGrams,
		arg.Price,
		arg.StockQuantity,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.GrindType,
		&i.WeightGrams,
		&i.Price,
		&i.StockQuantity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementVariantStock = `-- name: DecrementVariantStock :exec
UPDATE product_variants
SET stock_quantity = stock_quantity - $2
WHERE id = $1 AND stock_quantity >= $2
`

type DecrementVariantStockParams struct {
	ID            pgtype.UUID `json:"id"`
	StockQuantity int32       `json:"stock_quantity"`
}

func (q *Queries) DecrementVariantStock(ctx context.Context, arg DecrementVariantStockParams) error {
	_, err := q.db.Exec(ctx, decrementVariantStock, arg.ID, arg.StockQuantity)
	return err
}

const deleteVariant = `-- name: DeleteVariant :exec
DELETE FROM product_variants WHERE id = $1
`

func (q *Queries) DeleteVariant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariant, id)
	return err
}

const getVariantByID = `-- name: GetVariantByID :one
SELECT id, product_id, sku, grind_type, weight_grams, price, stock_quantity, is_active, created_at, updated_at FROM product_variants WHERE id = $1
`

func (q *Queries) GetVariantByID(ctx context.Context, id pgtype.UUID) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getVariantByID, id)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.GrindType,
		&i.WeightGrams,
		&i.Price,
		&i.StockQuantity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantForUpdate = `-- name: GetVariantForUpdate :one
SELECT id, product_id, sku, grind_type, weight_grams, price, stock_quantity, is_active, created_at, updated_at FROM product_variants WHERE id = $1 FOR UPDATE
`

// Locks the row so concurrent orders can't both pass a stock check on the
// same variant; used inside the order-creation transaction.
func (q *Queries) GetVariantForUpdate(ctx context.Context, id pgtype.UUID) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getVariantForUpdate, id)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.GrindType,
		&i.WeightGrams,
		&i.Price,
		&i.StockQuantity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVariantsByProductID = `-- name: ListVariantsByProductID :many
SELECT id, product_id, sku, grind_type, weight_grams, price, stock_quantity, is_active, created_at, updated_at FROM product_variants
WHERE product_id = $1 AND is_active = true
ORDER BY weight_grams ASC
`

func (q *Queries) ListVariantsByProductID(ctx context.Context, productID pgtype.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.GrindType,
			&i.WeightGrams,
			&i.Price,
			&i.StockQuantity,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE product_variants
SET sku = $2, grind_type = $3, weight_grams = $4, price = $5, stock_quantity = $6
WHERE id = $1
RETURNING id, product_id, sku, grind_type, weight_grams, price, stock_quantity, is_active, created_at, updated_at
`

type UpdateVariantParams struct {
	ID            pgtype.UUID    `json:"id"`
	Sku           string         `json:"sku"`
	GrindType     pgtype.Text    `json:"grind_type"`
	WeightGrams   int32          `json:"weight_grams"`
	Price         pgtype.Numeric `json:"price"`
	StockQuantity int32          `json:"stock_quantity"`
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.ID,
		arg.Sku,
		arg.GrindType,
		arg.WeightGrams,
		arg.Price,
		arg.StockQuantity,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.GrindType,
		&i.WeightGrams,
		&i.Price,
		&i.StockQuantity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVariantStock = `-- name: UpdateVariantStock :one
UPDATE product_variants
SET stock_quantity = $2
WHERE id = $1
RETURNING id, product_id, sku, grind_type, weight_grams, price, stock_quantity, is_active, created_at, updated_at
`

type UpdateVariantStockParams struct {
	ID            pgtype.UUID `json:"id"`
	StockQuantity int32       `json:"stock_quantity"`
}

func (q *Queries) UpdateVariantStock(ctx context.Context, arg UpdateVariantStockParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateVariantStock, arg.ID, arg.StockQuantity)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.GrindType,
		&i.WeightGrams,
		&i.Price,
		&i.StockQuantity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
