// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Returns count of existing (non-cancelled) catering bookings on a given date,
	// so the service layer can flag the date as busy without hard-blocking it.
	CheckDateAvailability(ctx context.Context, eventDate pgtype.Date) (int64, error)
	CountCustomerOrders(ctx context.Context, customerID pgtype.UUID) (int64, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error)
	CreateCateringDetails(ctx context.Context, arg CreateCateringDetailsParams) (CateringDetail, error)
	CreateCateringPackage(ctx context.Context, arg CreateCateringPackageParams) (CateringPackage, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateOrderStatusHistory(ctx context.Context, arg CreateOrderStatusHistoryParams) (OrderStatusHistory, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateVariant(ctx context.Context, arg CreateVariantParams) (ProductVariant, error)
	DecrementVariantStock(ctx context.Context, arg DecrementVariantStockParams) error
	DeleteCateringPackage(ctx context.Context, id pgtype.UUID) error
	DeleteProduct(ctx context.Context, id pgtype.UUID) error
	DeleteVariant(ctx context.Context, id pgtype.UUID) error
	GetAdminUserByID(ctx context.Context, id pgtype.UUID) (AdminUser, error)
	GetAdminUserByUsername(ctx context.Context, username string) (AdminUser, error)
	GetCateringDetailsByOrderID(ctx context.Context, orderID pgtype.UUID) (CateringDetail, error)
	GetCateringPackageByID(ctx context.Context, id pgtype.UUID) (CateringPackage, error)
	GetCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error)
	GetCustomerByPhone(ctx context.Context, phone string) (Customer, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrderByOrderNumber(ctx context.Context, orderNumber string) (Order, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error)
	GetProductBySlug(ctx context.Context, slug string) (Product, error)
	GetVariantByID(ctx context.Context, id pgtype.UUID) (ProductVariant, error)
	// Locks the row so concurrent orders can't both pass a stock check on the
	// same variant; used inside the order-creation transaction.
	GetVariantForUpdate(ctx context.Context, id pgtype.UUID) (ProductVariant, error)
	ListActiveCateringPackages(ctx context.Context) ([]CateringPackage, error)
	ListActiveProducts(ctx context.Context) ([]Product, error)
	// Admin customer list, newest first, optionally searched by name or phone.
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]ListOrderItemsByOrderIDRow, error)
	ListOrderStatusHistory(ctx context.Context, orderID pgtype.UUID) ([]OrderStatusHistory, error)
	// Admin order queue, newest first, optionally filtered by status.
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	// For the admin calendar view.
	ListUpcomingCateringBookings(ctx context.Context) ([]ListUpcomingCateringBookingsRow, error)
	ListVariantsByProductID(ctx context.Context, productID pgtype.UUID) ([]ProductVariant, error)
	NextOrderNumber(ctx context.Context) (int64, error)
	UpdateCateringPackage(ctx context.Context, arg UpdateCateringPackageParams) (CateringPackage, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ProductVariant, error)
	UpdateVariantStock(ctx context.Context, arg UpdateVariantStockParams) (ProductVariant, error)
}

var _ Querier = (*Queries)(nil)
